server:
  port: 8080

spring:
  application:
    name: devfolio-builder-api
  r2dbc:
    url: r2dbc:postgresql://${NEON_HOST:ep-example.us-east-2.aws.neon.tech}:5432/${NEON_DATABASE:pruebadb}?sslmode=require
    username: ${NEON_USER:tu_usuario}
    password: ${NEON_PASSWORD:tu_password}
    pool:
      initial-size: 5
      max-size: 20
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://ep-withered-salad-acdqzx2b.neonauth.sa-east-1.aws.neon.tech}
          jwk-set-uri: ${JWT_JWKS_URI:https://ep-withered-salad-acdqzx2b.neonauth.sa-east-1.aws.neon.tech/foliobuilderdevbd/auth/.well-known/jwks.json}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.security: DEBUG